### ISSUE TITLE
Freeze when changing resourcecomposition and deploying a new resourcecomposition

### ISSUE THREAD

**Issue by mikosa** [cloud-ark/kubeplus#708]
In any version of GKE (17, 18, or 19)
I found an issue when I try to move from one example being tested to another.

To reproduce,  deploy 
examples/multitenancy/stacks including the mysqlservicetenant and tenant1.
After it deploys, delete mysqlservicetenant. (tenant1 and the helm chart gets deleted as expected)

Next try to deploy another example like mongodb
when u run the mongodbservicetenant.yaml, it will take some time for the crd to appear. After that, create tenant1.yaml.
The helm chart will not deploy. and no deployment or statefulset appear.

To fix this, you will need to delete the mongodbservicetenant and tenant1 and manually delete the newly created CRD. when all are deleted, then if you try again and install mongodbservicetenant then wait for the CRD, and then deploy tenant1

So now, after creating mongodbservicetenant and deleting and then recreating mongodbservicetenant, the helm chart will appear and deploy the expected deployment 

I find this as an unexpected behavior.
I think in the operator, there are parts of the resourcecomponents that are not being deleted the first time maybe.

**Comment by devdattakulkarni** [comment]
Can you share the artifacts that you used for the Mongodb example? I am suspecting if this is happening because the Kind names are not unique (reference: https://github.com/cloud-ark/kubeplus/issues/696)

If you don't mind would you be able to create a PR against this repo adding mongodb example. You can add it as 
examples/crd4crd-mongodb

Please include the steps.txt, artifacts (yaml files) and also the Helm chart that you created for deploying the resources. I noticed that you have pushed a PR against the operatorchart repo to include the Mongodb operator chart. Is that Helm v3 chart?

**Comment by devdattakulkarni** [comment]
@mikosa We have made many improvements to KubePlus. This issue does not seem to be present anymore.

Something that will be interesting to you is - we have added support for Network metrics. Also, CPU and Memory metrics are now directly collected from the kubelet.

Let us know if the current feature set is something that can help you with your MongoDB-as-a-Service offering. We will be happy to add additional features as required.

**Comment by devdattakulkarni** [comment]
I am going to close this issue for now. We can reopen it if this is still a problem.

**Comment by devdattakulkarni** [comment]
@mikosa Hi!
We are starting KubePlus community meetings next week. They will be on Tuesdays at 10.30 a.m. US Central time. The meetings will be on #kubeplus Slack channel in the CNCF workspace. I hope you are able to join us for these meetings as we look forward to building KubePlus further with community inputs and involvement.
